package com.manikhweschool.book.java.part.one.chapter.three;

public enum ChapterThreeExerciseNumber {

	Three_One_A,Three_One_B,Three_One_C,
	Three_Two_A,Three_Two_B,Three_Two_C,
	Three_Three_A,Three_Three_B,Three_Three_C,
	Three_Four_A,Three_Four_B,Three_Four_C,
	Three_Five_A,Three_Five_B,Three_Five_C,
	Three_Six_A,Three_Six_B,Three_Six_C,
	Three_Seven_A,Three_Seven_B,Three_Seven_C,
	Three_Eight_A,Three_Eight_B,Three_Eight_C,
	Three_Nine_A,Three_Nine_B,Three_Nine_C,
	Three_Ten_A,Three_Ten_B,Three_Ten_C,	
	Three_Eleven_A,Three_Eleven_B,Three_Eleven_C,
	Three_Twelve_A,Three_Twelve_B,Three_Twelve_C,
	Three_Thirteen_A,Three_Thirteen_B,Three_Thirteen_C,
	Three_Fourteen_A,Three_Fourteen_B,Three_Fourteen_C,
	Three_Fifteen_A,Three_Fifteen_B,Three_Fifteen_C,
	Three_Sixteen_A,Three_Sixteen_B,Three_Sixteen_C,
	Three_Seventeen_A,Three_Seventeen_B,Three_Seventeen_C,
	Three_Eighteen_A,Three_Eighteen_B,Three_Eighteen_C,
	Three_Nineteen_A,Three_Nineteen_B,Three_Nineteen_C,
	Three_Twenty_A,Three_Twenty_B,Three_Twenty_C,
	Three_Twenty_One_A,Three_Twenty_One_B,Three_Twenty_One_C,
	Three_Twenty_Two_A,Three_Twenty_Two_B,Three_Twenty_Two_C,
	Three_Twenty_Three_A,Three_Twenty_Three_B,Three_Twenty_Three_C,
	Three_Twenty_Four_A,Three_Twenty_Four_B,Three_Twenty_Four_C,
	Three_Twenty_Five_A,Three_Twenty_Five_B,Three_Twenty_Five_C,
	Three_Twenty_Six_A,Three_Twenty_Six_B,Three_Twenty_Six_C,
	Three_Twenty_Seven_A,Three_Twenty_Seven_B,Three_Twenty_Seven_C,
	Three_Twenty_Eight_A,Three_Twenty_Eight_B,Three_Twenty_Eight_C,
	Three_Twenty_Nine_A,Three_Twenty_Nine_B,Three_Twenty_Nine_C,
	Three_Thirty_A,Three_Thirty_B,Three_Thirty_C,
	Three_Thirty_One_A,Three_Thirty_One_B,Three_Thirty_One_C,
	Three_Thirty_Two_A,Three_Thirty_Two_B,Three_Thirty_Two_C,
	Three_Thirty_Three_A,Three_Thirty_Three_B,Three_Thirty_Three_C,
	Three_Thirty_Four_A,Three_Thirty_Four_B,Three_Thirty_Four_C
}
