package com.manikhweschool.book.java.part.one.chapter.seven;

public enum ChapterSevenExerciseNumber {

	Seven_One_A,Seven_One_B,Seven_One_C,
	Seven_Two_A,Seven_Two_B,Seven_Two_C,
	Seven_Three_A,Seven_Three_B,Seven_Three_C,
	Seven_Four_A,Seven_Four_B,Seven_Four_C,
	Seven_Five_A,Seven_Five_B,Seven_Five_C,
	Seven_Six_A,Seven_Six_B,Seven_Six_C,
	Seven_Seven_A,Seven_Seven_B,Seven_Seven_C,
	Seven_Eight_A,Seven_Eight_B,Seven_Eight_C,
	Seven_Nine_A,Seven_Nine_B,Seven_Nine_C,
	Seven_Ten_A,Seven_Ten_B,Seven_Ten_C,	
	Seven_Eleven_A,Seven_Eleven_B,Seven_Eleven_C,
	Seven_Twelve_A,Seven_Twelve_B,Seven_Twelve_C,
	Seven_Thirteen_A,Seven_Thirteen_B,Seven_Thirteen_C,
	Seven_Fourteen_A,Seven_Fourteen_B,Seven_Fourteen_C,
	Seven_Fifteen_A,Seven_Fifteen_B,Seven_Fifteen_C,
	Seven_Sixteen_A,Seven_Sixteen_B,Seven_Sixteen_C,
	Seven_Seventeen_A,Seven_Seventeen_B,Seven_Seventeen_C,
	Seven_Eighteen_A,Seven_Eighteen_B,Seven_Eighteen_C,
	Seven_Nineteen_A,Seven_Nineteen_B,Seven_Nineteen_C,
	Seven_Twenty_A,Seven_Twenty_B,Seven_Twenty_C,
	Seven_Twenty_One_A,Seven_Twenty_One_B,Seven_Twenty_One_C,
	Seven_Twenty_Two_A,Seven_Twenty_Two_B,Seven_Twenty_Two_C,
	Seven_Twenty_Three_A,Seven_Twenty_Three_B,Seven_Twenty_Three_C,
	Seven_Twenty_Four_A,Seven_Twenty_Four_B,Seven_Twenty_Four_C,
	Seven_Twenty_Five_A,Seven_Twenty_Five_B,Seven_Twenty_Five_C,
	Seven_Twenty_Six_A,Seven_Twenty_Six_B,Seven_Twenty_Six_C,
	Seven_Twenty_Seven_A,Seven_Twenty_Seven_B,Seven_Twenty_Seven_C,
	Seven_Twenty_Eight_A,Seven_Twenty_Eight_B,Seven_Twenty_Eight_C,
	Seven_Twenty_Nine_A,Seven_Twenty_Nine_B,Seven_Twenty_Nine_C,
	Seven_Thirty_A,Seven_Thirty_B,Seven_Thirty_C,
	Seven_Thirty_One_A,Seven_Thirty_One_B,Seven_Thirty_One_C,
	Seven_Thirty_Two_A,Seven_Thirty_Two_B,Seven_Thirty_Two_C,
	Seven_Thirty_Three_A,Seven_Thirty_Three_B,Seven_Thirty_Three_C,
	Seven_Thirty_Four_A,Seven_Thirty_Four_B,Seven_Thirty_Four_C,	
	Seven_Thirty_Five_A,Seven_Thirty_Five_B,Seven_Thirty_Five_C
}
