package com.manikhweschool.book.java.part.one.chapter.six;

public enum ChapterSixExerciseNumber {

	Six_One_A,Six_One_B,Six_One_C,
	Six_Two_A,Six_Two_B,Six_Two_C,
	Six_Three_A,Six_Three_B,Six_Three_C,
	Six_Four_A,Six_Four_B,Six_Four_C,
	Six_Five_A,Six_Five_B,Six_Five_C,
	Six_Six_A,Six_Six_B,Six_Six_C,
	Six_Seven_A,Six_Seven_B,Six_Seven_C,
	Six_Eight_A,Six_Eight_B,Six_Eight_C,
	Six_Nine_A,Six_Nine_B,Six_Nine_C,
	Six_Ten_A,Six_Ten_B,Six_Ten_C,	
	Six_Eleven_A,Six_Eleven_B,Six_Eleven_C,
	Six_Twelve_A,Six_Twelve_B,Six_Twelve_C,
	Six_Thirteen_A,Six_Thirteen_B,Six_Thirteen_C,
	Six_Fourteen_A,Six_Fourteen_B,Six_Fourteen_C,
	Six_Fifteen_A,Six_Fifteen_B,Six_Fifteen_C,
	Six_Sixteen_A,Six_Sixteen_B,Six_Sixteen_C,
	Six_Seventeen_A,Six_Seventeen_B,Six_Seventeen_C,
	Six_Eighteen_A,Six_Eighteen_B,Six_Eighteen_C,
	Six_Nineteen_A,Six_Nineteen_B,Six_Nineteen_C,
	Six_Twenty_A,Six_Twenty_B,Six_Twenty_C,
	Six_Twenty_One_A,Six_Twenty_One_B,Six_Twenty_One_C,
	Six_Twenty_Two_A,Six_Twenty_Two_B,Six_Twenty_Two_C,
	Six_Twenty_Three_A,Six_Twenty_Three_B,Six_Twenty_Three_C,
	Six_Twenty_Four_A,Six_Twenty_Four_B,Six_Twenty_Four_C,
	Six_Twenty_Five_A,Six_Twenty_Five_B,Six_Twenty_Five_C,
	Six_Twenty_Six_A,Six_Twenty_Six_B,Six_Twenty_Six_C,
	Six_Twenty_Seven_A,Six_Twenty_Seven_B,Six_Twenty_Seven_C,
	Six_Twenty_Eight_A,Six_Twenty_Eight_B,Six_Twenty_Eight_C,
	Six_Twenty_Nine_A,Six_Twenty_Nine_B,Six_Twenty_Nine_C,
	Six_Thirty_A,Six_Thirty_B,Six_Thirty_C,
	Six_Thirty_One_A,Six_Thirty_One_B,Six_Thirty_One_C,
	Six_Thirty_Two_A,Six_Thirty_Two_B,Six_Thirty_Two_C,
	Six_Thirty_Three_A,Six_Thirty_Three_B,Six_Thirty_Three_C,
	Six_Thirty_Four_A,Six_Thirty_Four_B,Six_Thirty_Four_C,	
	Six_Thirty_Five_A,Six_Thirty_Five_B,Six_Thirty_Five_C,
	Six_Thirty_Six_A,Six_Thirty_Six_B,Six_Thirty_Six_C,
	Six_Thirty_Seven_A,Six_Thirty_Seven_B,Six_Thirty_Seven_C,
	Six_Thirty_Eight_A,Six_Thirty_Eight_B,Six_Thirty_Eight_C,
	Six_Thirty_Nine_A,Six_Thirty_Nine_B,Six_Thirty_Nine_C
}
